### ISSUE TITLE
Model Transition Likelihood Profile looks Suspect

### ISSUE THREAD

**Issue by Ovec8hkin** [JaneSullivan-NOAA/shortspine_thornyhead_2023#15]
@MatthVeron When looking at the likelihood profiles of virgin biomass for the 2013 v3.24 and 2013 v3.30.21, it looks like the 3.30 model may have fixed a parameter that is being estimated in the original 2013 model. Can you confirm that nothing got accidentally fixed during the transition? We should do some additional investigations to why the likelihood profiles are so different, as simply updating the SS version shouldn't have resulted in such a large change in the likelihood profile.

**Comment by MatthVeron** [comment]
@Ovec8hkin Sorry about this, I thought I precised it in class in addition to write it down in the transition script. That is "normal" that the likelihoods are different because I'm not estimating the catchability parameters in the new version of SS. This was to be sure the transition work. I wanted to implement two models to check the transition:
1- One with all parameters fixed
2- Another one where parameters are estimated as there were in the previous version
I'll try to get this done tomorrow (sorry for this).
Hope this help ;)
